"""Add Multi-Profile Architecture

Revision ID: 166ec1867d1d
Revises: 7ec32bcc77d4
Create Date: 2026-05-15 08:05:57.967235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166ec1867d1d'
down_revision: Union[str, Sequence[str], None] = '7ec32bcc77d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permissions', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_admin_profile_id'), 'admin_profile', ['id'], unique=False)
    op.create_table('customer_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_customer_profile_id'), 'customer_profile', ['id'], unique=False)
    op.create_table('vendor_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('subscription_tier', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_vendor_profile_id'), 'vendor_profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_profile_id'), table_name='vendor_profile')
    op.drop_table('vendor_profile')
    op.drop_index(op.f('ix_customer_profile_id'), table_name='customer_profile')
    op.drop_table('customer_profile')
    op.drop_index(op.f('ix_admin_profile_id'), table_name='admin_profile')
    op.drop_table('admin_profile')
    # ### end Alembic commands ###
