"""Add roles and scene ownership

Revision ID: 594d98a49ff0
Revises: 0051673a5f87
Create Date: 2026-05-15 07:27:13.900452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '594d98a49ff0'
down_revision: Union[str, Sequence[str], None] = '0051673a5f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the Enum type first
    user_role = sa.Enum('ADMIN', 'VENDOR', 'CUSTOMER', name='userrole')
    user_role.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene', sa.Column('vendor_id', sa.Integer(), nullable=False))
    op.add_column('scene', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('scene_user_id_fkey'), 'scene', type_='foreignkey')
    op.create_foreign_key(None, 'scene', 'user', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'scene', 'user', ['vendor_id'], ['id'])
    op.drop_column('scene', 'user_id')
    op.add_column('user', sa.Column('role', sa.Enum('ADMIN', 'VENDOR', 'CUSTOMER', name='userrole'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.add_column('scene', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'scene', type_='foreignkey')
    op.drop_constraint(None, 'scene', type_='foreignkey')
    op.create_foreign_key(op.f('scene_user_id_fkey'), 'scene', 'user', ['user_id'], ['id'])
    op.drop_column('scene', 'customer_id')
    op.drop_column('scene', 'vendor_id')
    # ### end Alembic commands ###
