"""Add pgvector support

Revision ID: 7ec32bcc77d4
Revises: 594d98a49ff0
Create Date: 2026-05-15 08:00:21.010335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec32bcc77d4'
down_revision: Union[str, Sequence[str], None] = '594d98a49ff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable the pgvector extension in PostgreSQL
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    import pgvector
    op.add_column('scene', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene', 'embedding')
    # ### end Alembic commands ###
